# -*- coding: utf-8 -*-
"""Student Record Management System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXylQmiN0JvQrfIuvlrtLwKm7R95aNvb
"""

import sqlite3

def connect_db():
    # Connect to SQLite database (or create it if it doesn't exist)
    conn = sqlite3.connect("students.db")
    cursor = conn.cursor()
    # Create the table if it doesn't exist
    cursor.execute('''CREATE TABLE IF NOT EXISTS students (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        name TEXT NOT NULL,
                        age INTEGER NOT NULL,
                        grade TEXT NOT NULL
                    )''')
    conn.commit()
    return conn

def add_student(conn, name, age, grade):
    cursor = conn.cursor()
    cursor.execute("INSERT INTO students (name, age, grade) VALUES (?, ?, ?)", (name, age, grade))
    conn.commit()
    print("Student added successfully!")

def view_students(conn):
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM students")
    records = cursor.fetchall()
    print("\nStudent Records:")
    print("ID | Name           | Age | Grade")
    print("-----------------------------------")
    for record in records:
        print(f"{record[0]:<3} | {record[1]:<14} | {record[2]:<3} | {record[3]}")

def update_student(conn, student_id, name, age, grade):
    cursor = conn.cursor()
    cursor.execute("UPDATE students SET name = ?, age = ?, grade = ? WHERE id = ?", (name, age, grade, student_id))
    conn.commit()
    if cursor.rowcount:
        print("Student updated successfully!")
    else:
        print("Student ID not found.")

def delete_student(conn, student_id):
    cursor = conn.cursor()
    cursor.execute("DELETE FROM students WHERE id = ?", (student_id,))
    conn.commit()
    if cursor.rowcount:
        print("Student deleted successfully!")
    else:
        print("Student ID not found.")

def main():
    conn = connect_db()
    while True:
        print("\nStudent Record Management System")
        print("1. Add Student")
        print("2. View Students")
        print("3. Update Student")
        print("4. Delete Student")
        print("5. Exit")
        choice = input("Enter your choice: ")

        if choice == "1":
            name = input("Enter name: ")
            age = int(input("Enter age: "))
            grade = input("Enter grade: ")
            add_student(conn, name, age, grade)

        elif choice == "2":
            view_students(conn)

        elif choice == "3":
            student_id = int(input("Enter student ID to update: "))
            name = input("Enter new name: ")
            age = int(input("Enter new age: "))
            grade = input("Enter new grade: ")
            update_student(conn, student_id, name, age, grade)

        elif choice == "4":
            student_id = int(input("Enter student ID to delete: "))
            delete_student(conn, student_id)

        elif choice == "5":
            conn.close()
            print("Exiting the program.")
            break

        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

